### PR TITLE
Replace outdate library underscore.string by voca to fix emoji issue

### PR DESCRIPTION
**Pull request by ycherniavskyi**
Currently `metalsmith-better-excerpts` plugin has the problem with emoji symbols because of the issue in `unescapeHTML` function of `underscore.string` library. The issue connected to `String.fromCharCode` function usage ([see code](https://github.com/epeli/underscore.string/blob/2f78f0d6e36d553484a1bf5fe5ed1998f013dea5/unescapeHTML.js#L12)) and detailed explained on stackoverflow question [Printing emojis with JavaScript and HTML](https://stackoverflow.com/questions/22312364/printing-emojis-with-javascript-and-html).

Unfortunately, as I see from GitHub repository of [underscore.string](https://github.com/epeli/underscore.string) project it did not support from 2016. So creating the issue to it is senseless.

Fortunately, exist almost identical [voca](https://github.com/panzerdp/voca) project. And just by replacing `underscore.string` by `voca` (with minimal code update) emoji symbols start processed correctly.

### CODE REVIEW

**Comment by ycherniavskyi** [comment]
Ups sorry forget about tests. I will revise errors and update my pull request shortly.

**Comment by simbo** [comment]
Thanks for the changes. It's already merged but it seems that i have to fix the travis config.
I will look into that asap, so the new version can be released.

**Comment by ycherniavskyi** [comment]
Great! Waiting for the new version in npm ☺️.

**Comment by simbo** [comment]
Released.

**Pull request merged**
